//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP_Restaurante_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int ReservaId { get; set; }
        public int ClienteId { get; set; }
        public int MesaId { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public byte DuracionHoras { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public byte NumeroPersonas { get; set; }
        public string Estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual mesa mesa { get; set; }
    }
}
